--------------------------------------------------------------------------
[[36674,1],3]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: bastet

Another transport will be used instead, although this may result in
lower performance.

NOTE: You can disable this warning by setting the MCA parameter
btl_base_warn_component_unused to 0.
--------------------------------------------------------------------------
FITNESS_0= 2 873.2238
FITNESS_0= 3 773.0022
FITNESS_0= 10 774.0621
FITNESS_0= 9 1371.8099
[bastet:69473] 11 more processes have sent help message help-mpi-btl-base.txt / btl:no-nics
[bastet:69473] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
FITNESS_0= 8 1371.8099
FITNESS_0= 11 474.49072
FITNESS_0= 6 375.55896
FITNESS_0= 0 76.28711
FITNESS_0= 1 77.03433
FITNESS_0= 4 77.09153
FITNESS_0= 5 76.68791
FITNESS_0= 7 773.28076
breedables shape= (12, 429)
addition= (429,)
addition= (429,)
addition= (429,)
addition= (429,)
addition= (429,)
addition= (429,)
Breeders Shape= (6, 429)
Breeders Shape 2= (6, 429)
TEMPS= 2 3
Shape= (6, 429)
TEMPS= 1120 871
Shape= (2572,)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/mpi4py/__main__.py", line 7, in <module>
xc    main()
  File "/usr/local/lib/python3.6/dist-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/usr/local/lib/python3.6/dist-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "ga_wrapper_elitism.py", line 258, in <module>
    newiparray,avgFit,parents,parentFits=gaIter(recvbuf,iparray,parentArray,parentFitArray,i)
  File "ga_wrapper_elitism.py", line 232, in gaIter
    newIParray,parents,parentFits=getNextGeneration(breeders,breederFits)
  File "ga_wrapper_elitism.py", line 202, in getNextGeneration
    p1=breeders[temp1,:]
IndexError: too many indices for array
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
